[package]
name = "stassh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "stassh"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
libc.workspace = true
rpassword.workspace = true
serde_json.workspace = true
stassh-core = { path = "../../crates/stassh-core" }
uuid.workspace = true
zeroize.workspace = true
