use std::collections::{HashMap, HashSet};

use uuid::Uuid;

use crate::model::Vault;
use crate::openssh::forward_config_line;

pub fn export_openssh_config(vault: &Vault) -> String {
    let aliases = export_aliases(vault);
    let mut output = String::new();
    output.push_str("# Generated by stassh\n");
    output.push_str("# Review before replacing an existing OpenSSH config.\n\n");

    for host in &vault.hosts {
        let alias = aliases
            .get(&host.id)
            .expect("export aliases are generated for every host");

        output.push_str(&format!("# stassh-id: {}\n", host.id));
        output.push_str(&format!("# stassh-path: {}\n", vault.host_path(host)));
        output.push_str(&format!("Host {alias}\n"));
        output.push_str(&format!("    HostName {}\n", host.hostname));
        if host.port != 22 {
            output.push_str(&format!("    Port {}\n", host.port));
        }
        if let Some(username) = &host.username {
            output.push_str(&format!("    User {username}\n"));
        }
        if !host.jump_chain.is_empty() {
            let jump_aliases = host
                .jump_chain
                .iter()
                .filter_map(|jump_id| aliases.get(jump_id))
                .cloned()
                .collect::<Vec<_>>();
            if !jump_aliases.is_empty() {
                output.push_str(&format!("    ProxyJump {}\n", jump_aliases.join(",")));
            }
        }
        for forward in &host.forwards {
            output.push_str(&format!("    {}\n", forward_config_line(forward)));
        }
        for option in &host.ssh_options {
            output.push_str(&format!("    {option}\n"));
        }
        output.push('\n');
    }

    output
}

fn export_aliases(vault: &Vault) -> HashMap<Uuid, String> {
    let mut display_name_counts = HashMap::<&str, usize>::new();
    for host in &vault.hosts {
        *display_name_counts
            .entry(host.display_name.as_str())
            .or_default() += 1;
    }

    let mut used = HashSet::new();
    let mut aliases = HashMap::new();
    for host in &vault.hosts {
        let candidate = if display_name_counts[host.display_name.as_str()] == 1
            && is_safe_openssh_alias(&host.display_name)
        {
            host.display_name.clone()
        } else {
            format!("stassh-{}", host.id.simple())
        };

        let alias = if used.insert(candidate.clone()) {
            candidate
        } else {
            format!("stassh-{}", host.id.simple())
        };
        aliases.insert(host.id, alias);
    }
    aliases
}

fn is_safe_openssh_alias(value: &str) -> bool {
    !value.is_empty()
        && value
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.' | ':'))
        && !value.starts_with('-')
        && !value.contains('*')
        && !value.contains('?')
        && !value.contains('!')
}

#[cfg(test)]
mod tests {
    use crate::model::{AddHost, ForwardDefinition, HostSelector};

    use super::*;

    #[test]
    fn exports_basic_host_as_openssh_block() {
        let mut vault = Vault::new();
        vault
            .add_host(AddHost {
                folder_id: None,
                display_name: "web".to_string(),
                hostname: "web.example.com".to_string(),
                port: Some(2222),
                username: Some("deploy".to_string()),
                identity_fingerprint: None,
                jump_chain: Vec::new(),
                ssh_options: vec!["IdentityFile ~/.ssh/web".to_string()],
                forwards: vec![ForwardDefinition::Dynamic {
                    bind_address: "127.0.0.1".to_string(),
                    local_port: 1080,
                }],
                tags: Vec::new(),
                notes: None,
            })
            .unwrap();

        let exported = export_openssh_config(&vault);

        assert!(exported.contains("Host web\n"));
        assert!(exported.contains("    HostName web.example.com\n"));
        assert!(exported.contains("    Port 2222\n"));
        assert!(exported.contains("    User deploy\n"));
        assert!(exported.contains("    DynamicForward 127.0.0.1:1080\n"));
        assert!(exported.contains("    IdentityFile ~/.ssh/web\n"));
    }

    #[test]
    fn exports_proxy_jump_using_exported_alias() {
        let mut vault = Vault::new();
        let jump = vault
            .add_host(AddHost {
                folder_id: None,
                display_name: "bastion".to_string(),
                hostname: "bastion.example.com".to_string(),
                port: None,
                username: None,
                identity_fingerprint: None,
                jump_chain: Vec::new(),
                ssh_options: Vec::new(),
                forwards: Vec::new(),
                tags: Vec::new(),
                notes: None,
            })
            .unwrap();
        vault
            .add_host(AddHost {
                folder_id: None,
                display_name: "db".to_string(),
                hostname: "10.0.0.5".to_string(),
                port: None,
                username: None,
                identity_fingerprint: None,
                jump_chain: vec![jump.id],
                ssh_options: Vec::new(),
                forwards: Vec::new(),
                tags: Vec::new(),
                notes: None,
            })
            .unwrap();

        let exported = export_openssh_config(&vault);

        assert!(exported.contains("Host bastion\n"));
        assert!(exported.contains("Host db\n"));
        assert!(exported.contains("    ProxyJump bastion\n"));
    }

    #[test]
    fn duplicate_or_unsafe_names_fall_back_to_stable_aliases() {
        let mut vault = Vault::new();
        let first = vault
            .add_host(AddHost {
                folder_id: None,
                display_name: "db".to_string(),
                hostname: "db1.example".to_string(),
                port: None,
                username: None,
                identity_fingerprint: None,
                jump_chain: Vec::new(),
                ssh_options: Vec::new(),
                forwards: Vec::new(),
                tags: Vec::new(),
                notes: None,
            })
            .unwrap();
        let second = vault
            .add_host(AddHost {
                folder_id: None,
                display_name: "db".to_string(),
                hostname: "db2.example".to_string(),
                port: None,
                username: None,
                identity_fingerprint: None,
                jump_chain: Vec::new(),
                ssh_options: Vec::new(),
                forwards: Vec::new(),
                tags: Vec::new(),
                notes: None,
            })
            .unwrap();
        vault
            .add_host(AddHost {
                folder_id: None,
                display_name: "bad name".to_string(),
                hostname: "bad.example".to_string(),
                port: None,
                username: None,
                identity_fingerprint: None,
                jump_chain: Vec::new(),
                ssh_options: Vec::new(),
                forwards: Vec::new(),
                tags: Vec::new(),
                notes: None,
            })
            .unwrap();

        let exported = export_openssh_config(&vault);

        assert!(exported.contains(&format!("Host stassh-{}\n", first.id.simple())));
        assert!(exported.contains(&format!("Host stassh-{}\n", second.id.simple())));
        assert!(exported.contains("# stassh-path: bad name\n"));
        assert!(!exported.contains("Host bad name\n"));

        assert!(vault.resolve_host(HostSelector::Id(first.id)).is_ok());
    }
}
