[package]
name = "stassh-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "stassh-tui"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
libc.workspace = true
ratatui.workspace = true
stassh-core = { path = "../../crates/stassh-core" }
uuid.workspace = true
zeroize.workspace = true
